version: 2
jobs:
  test_node_lts:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - farmacia-de-turno-react-{{ .Branch }}-{{ checksum "yarn.lock"}}
            - farmacia-de-turno-react-{{ .Branch }}-
            - farmacia-de-turno-react-
      - run: 'yarn install'
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: farmacia-de-turno-react-{{ .Branch }}-{{ checksum "yarn.lock"}}
      - run: 'yarn test'
  release:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: farmacia-de-turno-react-{{ .Branch }}-{{ checksum "yarn.lock"}}
      - run: 'yarn install'
      - save_cache:
          key: farmacia-de-turno-react-{{ .Branch }}-{{ checksum "yarn.lock"}}
          paths:
            - 'node_modules'

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test_node_lts
      - release:
          requires:
            - test_node_lts
