version: 2
jobs:
  test_node_lts:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: farmacia-de-turno-react-{{ .Branch }}-{{ checksum "package-lock.json"}}
      - run: 'npm install'
      - save_cache:
          key: farmacia-de-turno-react-{{ .Branch }}-{{ checksum "package-lock.json"}}
          paths: 'node_modules'
      - run: 'npm run test'
  release:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: farmacia-de-turno-react-{{ .Branch }}-{{ checksum "package-lock.json"}}
      - run: 'npm install'
      - save_cache:
          key: farmacia-de-turno-react-{{ .Branch }}-{{ checksum "package-lock.json"}}
          paths:
            - 'node_modules'

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test_node_lts
      - release:
          requires:
            - test_node_lts
